influxdb/influxdb.com

config.toml, content/docs/index.md, content/docs/v0.9/index.md, layouts/partials/nav.html, layouts/section/docs.html
=> Hook up main docs page in top bar and docs/index

content/docs/v0.9/introduction/installation.md
D/l'd file didn't match name in next statement of instructions
=> Fix install instructions

content/docs/v0.9/concepts/reading_and_writing_data.md
In the documentation, in the basic read/write example of writing multiple records at once, if the payload starts with new line, it does not work.
=> Read/write example: POST payload must not start with new line.

content/docs/v0.9/introduction/getting_started.md
Fixing a typo. "tags" should be singular in the following sentence:
"...with the measurement name of cpu and **tags** host has now been written..."
Found on https://influxdb.com/docs/v0.9/introduction/getting_started.html
=> fix typo ("tags" should be "tag")

content/docs/v0.9/clients/shell.md
Solved issue [56](https://github.com/influxdb/influxdb.com/issues/56).
Link now leads to `/docs/v0.9/query_language/querying_data.html` instead of `/docs`
=> Fix bad link in CLI documentation

content/docs/v0.9/query_language/querying_data.md
As noted in [53](https://github.com/influxdb/influxdb.com/issues/53),
the current query returns `{"results":[{"error":"database name
required"}]}`. To remedy this, I specify a database `mydb`.
=> Change first curl example to specify a database

content/docs/v0.9/concepts/reading_and_writing_data.md
The `Reading and Writing Data` section mentions how to specify a
retention policy, but lacks a reference to more information about
retention policies. Solves issue [54](https://github.com/influxdb/influxdb.com/issues/54)
=> Add retention policy management reference

content/docs/v0.9/administration/administration.md, content/docs/v0.9/query_language/spec.md
Was playing with the latest nightly build, ran into an issue trying to show retention policies. Looks like syntax got updated recently. https://github.com/influxdb/influxdb/commit/ee8ba11c4fdb30f5ae5c7d1c468d7985bf2232fd
Looks like this syntax does NOT work with 0.9.1. Not sure what the style guideline would be here for denoting differences between minor versions. I'll gladly update this PR if there's an example of how to show 0.9.1 syntax vs 0.9.2.
Thanks!
=> show retention policies now requires "ON"

content/docs/v0.9/query_language/data_exploration.md
In response to https://github.com/influxdb/influxdb.com/issues/121 chunk
size was documented
=> Document `chunk_size` query param

content/docs/v0.9/query_language/data_exploration.md
Use the correct regex flag syntax for case insensitive matching.
=> Use correct case insensitive regex flag syntax

content/docs/v0.6/introduction/installation.md, content/docs/v0.7/introduction/installation.md, content/docs/v0.8/introduction/installation.md, content/docs/v0.9/introduction/installation.md, content/site/chronograf-download.md, content/site/download.md
When installing packages on RPM based systems the best practice
is to use the command "yum localinstall" not "rpm".  This mananges
any dependencies on behalf of the user.  While influxdb should be
self sufficient, it's best to rely on the package manager and not
it's primitives.
=> fix: Specify "yum" not "rpm"

content/docs/v0.9/write_protocols/write_syntax.md
just a tiny correction.
I also spotted that the documentation lacks the fact (or I missed it at least) that lines starting with '#' are ignored.
=> Correct two spelling mistakes in write_syntax.md

content/site/download.md
Apparently the latest stable is 0.9.2.1 rather than 0.9.2. It's a bit confusing for people how are visiting website without checking the github.
Is it a missed point or there is a reason to have a link to 0.9.2?
=> Update download.md with correct links

content/docs/v0.9/concepts/glossary.md, content/docs/v0.9/write_protocols/write_syntax.md
In response to https://github.com/influxdb/influxdb.com/issues/258 the
mention of integers was removed from the `glossary`
=> Remove integer example from glossary

content/docs/v0.9/clients/api.md
From support email:
>Hi again, guys!
>Just wanted you to know, that I've developed also a Rust driver for the InfluxDB 0.9.3.
>https://github.com/gobwas/influent.rs
>Regards,
>Sergey Kamardin.
=> Add rust libary from support email

content/docs/v0.9/introduction/installation.md, content/docs/v0.9/introduction/overview.md, content/docs/v0.9/troubleshooting/frequently_encountered_issues.md
Realized the version numbers in `installation.md` and `overview.md` were 0.9.4, not 0.9.4.1 and changed them.
Also added an alias for the old troubleshooting page that is now the frequently encountered issues page.
=> update version number, add alias

content/docs/v0.9/query_language/schema_exploration.md
I restructured schema_exploration.md and all the examples now use the same database as the newer data_exploration.md.
There's also a new section on `SHOW DATABASES`.
=> add show databases and restructure schema_exploration.md

content/docs/v0.9/guides/clustering.md
Both sysvinit and systemd use /etc/default/influxdb so the instructions can
be simplified.
=> Use /etc/default/influxdb in cluster instructions

content/docs/v0.9/troubleshooting/frequently_encountered_issues.md
=> Negative timestamps are valid

content/docs/v0.9/introduction/installation.md
Few changes to the Installation page, namely:
* I updated the language flag on the markdown code samples to be `shell` instead of `bash` or `sh`. My only goal here was to make the flags consistent.
* I updated the `start` commands to use `service` instead of `/etc/init.d/influxdb`. This ensures that these commands are able to be used on systemd distributions without issue. #298 
* I changed the "Hosting on AWS" section to point to modifying the `/etc/default/influxdb` file instead of `/etc/init.d/influxdb` (for systemd). I also added a section on permissions, since the original section relied on modifying the init script.
The goal with these changes was to make all commands agnostic to the init system.
=> Updated systemd installation page

content/docs/v0.9/query_language/database_management.md
`IF NOT EXISTS` is before the database name rather than after.
I double checked master to make sure it hasn't changed in v0.9.5:
https://github.com/influxdb/influxdb/blob/a3d127f797fec3ae24d10dda5bedb498bcab87eb/influxql/parser_test.go#L1184
=> Corrects CREATE DATABASE IF NOT EXISTS grammar

content/docs/v0.9/query_language/functions.md
Format changes:
* Standardized the explanations of each function.
* Used the same sample data as the other InfluxQL docs for the examples.
Updates to content:
* `MIN()`, `MAX()`, `FIRST()`, `LAST()` now output the relevant timestamp instead of epoch 0 - added a note explaining InfluxDB's behavior in versions prior to 0.9.5.
* Made substantial edits to the explanation of `DERIVATIVE()`.
* Added discussions about `TOP()`, `BOTTOM()`, and `NON_NEGATIVE_DERIVATIVE()`.
* Added section about `AS` - we removed this from `data_exploration.md` and it should live somewhere.
`DERIVATIVE()`, `TOP()`, and `BOTTOM()` are new to me - any feedback on those sections would be particularly appreciated. When in doubt as to whether to include something about those functions I included it - the explanations …
=> edit and add to functions.md

content/docs/v0.9/query_language/data_exploration.md, content/docs/v0.9/query_language/functions.md, content/docs/v0.9/query_language/schema_exploration.md, content/docs/v0.9/sample_data/data_download.md
I created a new page `data_download.md` which gives instructions for downloading and writing the sample data to InfluxDB.
`data_exploration`, `schema_exploration`, and `functions` link to that page.
=> Add sample data download page and link to it from relevant documents

content/site/download.md
Fixing download link for the 0.9.5 RC2 RPM download.
=> Fix for RC2 RPM Downloads link

content/docs/v0.9/concepts/crosswalk.md
Changed line 125 from "SELECT * FROM foodships WHERE time > now() -1h" to "SELECT * FROM foodships WHERE time > now() - 1h" as it doesn't work without a whitespace after the '-' character and might cause confusion.
Also removed "a function in progress" comment for DERIVATIVE as the function has been implemented and documented.
=> typo fix when subtracting time & comment removal

content/docs/v0.9/write_protocols/write_syntax.md
Removed misleading references of curl commands using POST method while passing attributes with data-urlencode. This does not apply, as the string defined in data-urlencode when using a POST method is passed to the content instead of getting appended to the URL.
Troubleshooting and justification:
---
POST method with attributes defined in data-urlencode section. The string is not appended to the POST URL, rather it is added in the content along with the measurement data.
curl -vvvX POST 'http://localhost:8089/write' --data-urlencode 'db=mydb' --data-binary 'disk_free,hostname=server01 value=442221834240i'
[kostas@localhost ~]$ sudo nc -l -p 8089
POST /write HTTP/1.1
User-Agent: curl/7.29.0
Host: localhost:8089
Accept: */*
Content-Length: 55
Content-Type: application/x-www-form-urlencoded …
=> removed references to POST with --data-urlencode

content/site/download.md
Looks like I never merged the 0.2.1 PR, so just jump straight to 0.2.2
=> Telegraf: bump version to 0.2.2
