- content/site/contact.md
> Replace contact form with email

- content/site/support.md
- static/css/style.css
> Fix mobile table styling on support page

- content/docs/v0.9/concepts/authentication_and_authorization.md
Influx gang - I'm in the process of setting up influxdb locally and have been playing with authentication; it seems that the docs on the matter might be slightly off (or the config file is incorrectly structured, which I'm inclined to not believe).
> proposed change to the authorization docs

- content/docs/v0.9/administration/config.md
- content/docs/v0.9/concepts/clustering.md
> Remove incorrect info from clustering page

- content/docs/v0.9/query_language/functions.md
Not sure this explanation is entire correct but based on discussion here https://github.com/influxdb/influxdb/issues/2699# and my own testing this seems to be the new behavior.
This is for issue https://github.com/influxdb/influxdb.com/issues/103
> Update 0.9 derivative

- content/docs/v0.9/concepts/clustering.md
I noticed there were a few mistakes in the clustering documentation while I was trying to get clustering to so I fixed them.
Thanks!
> updated clustering documentation based on my experience

- content/docs/v0.9/guides/writing_data.md
line protocol doesn't (yet) support them, JSON protocol deprecated, let's not mention them for now.
> raw bytes no longer valid

- content/docs/v0.9/administration/backup_and_restore.md
By default snapshotting is disabled.
> Fix lie in docs

- content/docs/v0.9/query_language/functions.md
Looking for feedback on definition
> Rework derivative definition

- content/docs/v0.9/tools/shell.md
> remove `dump`

- content/docs/v0.9/about/release_notes.md
Looking for more things to add here.
> Add release notes section for 0.9.2

- content/blog/2015/07/23/InfluxDB-0_9_2_released-with-groundwork-for-clustering.md
it's not released yet, but will be in a few hours. For when that time comes...
> Add 0.9.2 release announcement

- content/docs/v0.9/introduction/installation.md
- content/site/download.md
> Bump version to 0.9.2

- content/docs/v0.9/clients/api.md
Documentation for this module can be found at https://metacpan.org/pod/AnyEvent::InfluxDB
> Added AnyEvent::InfluxDB Perl non-blocking library

- content/docs/v0.9/query_language/data_exploration.md
- content/docs/v0.9/query_language/functions.md
In response to [87](https://github.com/influxdb/influxdb.com/issues/87), more examples were added.
> Add more examples of absolute time

- content/docs/v0.9/clients/api.md
fixes https://github.com/influxdb/influxdb.com/issues/158
> adding new perl library

- content/docs/v0.8/introduction/installation.md
Someone created a tap so Homebrew works again.
> restoring OS X installation instructions

- content/docs/v0.9/query_language/spec.md
> removing DELETE

- content/docs/v0.9/concepts/schema_and_data_layout.md
> removing cardinality note

- content/docs/v0.9/concepts/glossary.md
- content/docs/v0.9/guides/troubleshooting.md
- content/docs/v0.9/guides/writing_data.md
- content/docs/v0.9/introduction/getting_started.md
- content/docs/v0.9/write_protocols/line.md
- content/docs/v0.9/write_protocols/write_syntax.md
Documentation for the new integer specification were added.
> Update documentation for integer values.

- config-new.toml
- config-production.toml
- config.toml
- layouts/docs/single.html
- static/css/style.css
Fixes https://github.com/influxdb/influxdb.com/issues/162
> Make h2 headers in the docs linkable

- content/docs/v0.9/administration/administration.md
> repairing RP admin section

- content/docs/v0.9/guides/writing_data.md
Only values can have problems when a trying to insert a different type. Tags don't have this problem.
> Only values can have problems when a trying to insert a different type

- content/docs/v0.9/write_protocols/write_syntax.md
partially fixes #173 (no note about default encoding)
> clarify escaping

- content/docs/v0.9/concepts/crosswalk.md
Fixed a couple typos and altered some of the formatting.
> Fix typos and formatting

- content/docs/v0.9/guides/clustering.md
> fix small typos and change some formatting

- content/docs/v0.9/write_protocols/json.md
> deprecating JSON write protocol

- content/docs/v0.9/guides/clustering.md
As noted by Philip, all of the clustering features are not fully function. I simply added a warning of this.
> Add warning about clustering features

- content/site/download.md
> bump telegraf to 0.1.7

- content/docs/v0.9/introduction/installation.md
> Bump v0.9 installation docs to 0.9.3

- content/docs/v0.9/administration/backup_and_restore.md
As a new user, it was difficult to find out how to do this, and I ultimately ended up digging into the source to find out if it was possible. This surfaces the information on the first place that I checked when I was looking for it.
> Add info on capturing remote backups

- content/docs/v0.9/tools/shell.md
> clarifying compatibility

- content/docs/v0.9/guides/writing_data.md
Made significant changes to the structure of the Writing Data guide and altered some of the content covered.
> Edits to the Writing Data Guide

- content/docs/v0.9/administration/config.md
> removing alpha clustering note

- content/docs/v0.9/guides/querying_data.md
Made changes to the structure of the Querying Data guide and added a section on the `chunk_size` parameter.
> make content and structural changes to querying edits guide

- content/docs/v0.9/query_language/functions.md
fixes #178, among other things
> add eventual functions, split, alphabetize

- content/docs/v0.9/write_protocols/udp.md
- layouts/partials/docs/v0.9/sidebar.html
Fixes https://github.com/influxdb/influxdb.com/issues/102
> Add new UDP page

- content/docs/v0.9/introduction/installation.md
Fixes https://github.com/influxdb/influxdb.com/issues/122
> Add rough draft of AWS info

- content/docs/v0.9/troubleshooting/system_monitoring.md
- layouts/partials/docs/v0.9/sidebar.html
https://github.com/influxdb/influxdb.com/issues/314
> add system monitoring page to troubleshooting section

- content/docs/v0.9/guides/clustering.md
Feels contrived, but fixes https://github.com/influxdb/influxdb.com/issues/170
> Add note about the output of show servers from cli

- content/docs/v0.9/concepts/08_vs_09.md
- content/docs/v0.9/query_language/data_exploration.md
> order by wired up as of 0.9.4

- content/docs/v0.9/guides/clustering.md
- content/docs/v0.9/introduction/installation.md
- content/docs/v0.9/introduction/overview.md
- content/site/download.md
Update version numbers to 0.9.4.
> 0.9.4 updates

- content/blog/2015/09/21/influxdb_week_in_review.md
@rkuchan this is the post for Monday morning - it just needs to be merged and have the new assets pushed to S3. thanks!
> Post for 9/21 "InfluxDB Week In Review"

- content/blog/2015/09/23/announcing_telegraf_0_1_9.md
/cc @pauldix @toddboom Does this sound better?
> Make the 'Clustering' announcement a little more subtle

- layouts/site/support.html
https://github.com/influxdb/influxdb.com/issues/331
> fix issue #331

- static/css/style.css
- makes your site more readable on mobile devices
https://github.com/influxdb/influxdb.com/commit/339bbbdffa8994a1670833d176d95547b7052225
before:
after:
> decrease padding on small devices

- content/docs/v0.9/query_language/data_exploration.md
Made significant changes to the Data Exploration page. I updated the content - all examples refer to the same sample data - and I reorganized the structure.
> update and reorganize data_exploration

- content/docs/v0.9/query_language/spec.md
Issues:
https://github.com/influxdb/influxdb.com/issues/273
https://github.com/influxdb/influxdb.com/issues/203
https://github.com/influxdb/influxdb.com/issues/265
> Update spec page

- content/site/download.md
> Add windows installer to downloads page

- content/docs/v0.9/concepts/index.md
Fixes
https://github.com/influxdb/influxdb.com/issues/375
> fix BoltDB mention

- content/docs/v0.9/write_protocols/write_syntax.md
fixes https://github.com/influxdb/influxdb.com/issues/228
> issue #228

- content/docs/v0.9/concepts/08_vs_09.md
- content/docs/v0.9/troubleshooting/frequently_encountered_issues.md
> adding sequence numbers

- content/docs/v0.9/query_language/math_operators.md
Problem highlighted in the doc on Mathematical Operators is now fixed with a temporary solution. Update the doc to reflect current status and quote from Philip O'Toole, author of the fix.
> Update doc with current temp fix for bug.

- content/blog/2015/10/09/windows_installer_times_series_database.md
@toddboom @beckettsean @corylanou
> Edits to Windows blog post

- content/docs/v0.9/query_language/query_syntax.md
> rp not valid query string param for reads

- content/docs/v0.9/write_protocols/udp.md
> Updated UDP documentation to point to UDP Github README.

- content/docs/v0.9/query_language/schema_exploration.md
- content/docs/v0.9/troubleshooting/system_monitoring.md
Fixes https://github.com/influxdb/influxdb.com/issues/288
> fixes issue#288

- content/docs/v0.9/administration/authentication_and_authorization.md
- content/docs/v0.9/query_language/database_management.md
Remove any mention of `ALTER DATABASE` from database_management.md and authentication_and_authorization.md.
Fixes https://github.com/influxdb/influxdb.com/issues/414
> Remove ALTER DATABASE 

- content/docs/v0.9/administration/authentication_and_authorization.md
- content/docs/v0.9/guides/querying_data.md
Correct aliases in authentication_and_authorization.md - my bad.
Fixes: https://github.com/influxdb/influxdb.com/issues/412
Thanks, @malteo for catching this!
> fix links to authentication_and_authorization.md

- content/docs/v0.9/query_language/database_management.md
- content/docs/v0.9/query_language/schema_exploration.md
Made these changes while reviewing current content. Merge or close, whatever makes most sense to you.
> Some minor tweaks to docs

- content/docs/v0.9/concepts/glossary.md
- content/docs/v0.9/concepts/key_concepts.md
Edits to `glossary.md`
---
* Alphabetize it!
* Link to docs where possible
* Add 'Related entries' to entries that reference other Glossary terms 
* Add entries for identifier, hinted handoff, query
In general, I tried to make the glossary colder - I removed examples and some longer explanations as I tried to incorporate that kind of discussion in `key_concepts.md`.
Edits to `key_concepts.md`
---
I **tried** to make this more of a general, gradual introduction to InfluxDB's data structure and concepts. It attempts to tell the InfluxDB story through simple example data. 👀s note where I made possibly not-OK simplifications or where I'd like some feedback - but in general, feedback on the whole thing would be great!
To do: 
* Add wal, shard, shard group, storage engines (tsm1,b1,bz1) to …
> edit glossary.md and key_concepts.md

- content/docs/v0.9/introduction/getting_started.md
> removing incorrect note

- content/docs/v0.9/introduction/installation.md
Hi InfluxBD people,
I added missing documentation on how to install InfluxDB on [FreeBSD](https://www.freebsd.org) and [PC-BSD](https://pcbsd.org).
Cheers,
tpltnt
> installation info for FreeBSD/PC-BSD

- content/blog/2015/10/12/influxdb_week_in_review.md
- content/blog/2015/10/19/influxdb_week_in_review.md
- content/blog/2015/10/26/influxdb_week_in_review.md
> Fix summary on Week in Review blog posts

- content/docs/v0.9/clients/api.md
Fixes https://github.com/influxdb/influxdb.com/issues/443
> add .Net client library to list of client libraries

- content/docs/v0.9/introduction/installation.md
Fixes https://github.com/influxdb/influxdb.com/issues/440
> Add windows install instructions to install page

- content/docs/v0.9/concepts/api.md
Fixes https://github.com/influxdb/influxdb.com/issues/438 https://github.com/influxdb/influxdb.com/issues/439
> add wait_for_timeout instructions on /ping endpoint

- content/blog/2015/09/16/InfluxDB-0_9_4-released-with-top-order-by-time-desc-and-more.md
- content/blog/2015/09/22/monitoring_internal_show_stats.md
- content/blog/2015/10/20/testing_tsm.md
- content/docs/v0.8/introduction/installation.md
- content/docs/v0.9/concepts/08_vs_09.md
- content/docs/v0.9/concepts/index.md
- content/docs/v0.9/introduction/installation.md
- content/docs/v0.9/troubleshooting/frequently_encountered_issues.md
Believe I signed a CLA when this was influxdb.org.
> Copy edits for typos.

- content/docs/v0.9/guides/writing_data.md
> Fixing a typo

- content/site/download.md
I'm assuming the content here is okay. My main concern is on the formatting of the page, since the checksums appear a little dis-jointed from the downloads themselves. 
Let me know if I should modify anything.
> Added MD5 checksums to download page

- content/docs/v0.9/write_protocols/udp.md
this should go in once https://github.com/influxdb/influxdb/pull/4676 is merged
> Update udp doc with UDP buffer size note and read-buffer arg

- content/docs/v0.9/guides/writing_data.md
Fixes https://github.com/influxdb/influxdb.com/issues/357
> Add note to writing points from a file

- content/docs/v0.9/write_protocols/write_syntax.md
Correct escaping rules for measurements.
> Correct escaping rules documentation

- content/docs/v0.9/introduction/getting_started.md
Fixes https://github.com/influxdb/influxdb.com/issues/472
> Reformat CLI output on Getting Started

- content/docs/v0.9/administration/statistics.md
Fixes https://github.com/influxdb/influxdb.com/issues/477.
> Update blurb on internal monitoring

- content/site/download.md
Fixes https://github.com/influxdb/influxdb.com/issues/481.
@otoolep
> Clarify nightly build description

- content/docs/v0.9/introduction/getting_started.md
Made a few edits to the Getting Started page.
> Small changes to the getting started guide

- content/blog/2015/11/13/influxdb_slack_channel.md
- content/blog/2015/11/17/influx-slack-channel-announcement
> Announcement for influxdb slack channel

- content/docs/v0.9/write_protocols/line.md
> insert booltest bool=TRUE
> insert booltest bool=True
> insert booltest bool=true
> insert booltest bool=t
> insert booltest bool=T
> select * from booltest where bool=True
name: booltest
--------------
2015-11-16T11:04:27.990180325Z	true
2015-11-16T11:04:36.917791109Z	true
2015-11-16T11:04:40.763112553Z	true
2015-11-16T11:04:46.241617639Z	true
2015-11-16T11:04:47.597209692Z	true
> insert booltest bool=FALSE
> insert booltest bool=False
> insert booltest bool=false
> insert booltest bool=f
> insert booltest bool=F
> select * from booltest where bool=False
name: booltest
--------------
time				bool
2015-11-16T11:05:37.08689252Z	false
2015-11-16T11:05:39.299133295Z	false
2015-11-16T11:05:41.067252121Z	false
2015-11-16T11:05:44.439235925Z	false
2015-11-16T11:05:45.771210411Z	false
> added True and False to acceptable boolean values

- content/docs/v0.9/clients/api.md
Adding node-influx to supported javascript/node.js client libraries.
> Adding node-influx.

- content/docs/v0.9/guides/clustering.md
- content/docs/v0.9/introduction/getting_started.md
- content/docs/v0.9/introduction/installation.md
- content/docs/v0.9/tools/shell.md
> Updated references to old (pre-v0.9.5) directory structure.

- content/docs/v0.9/administration/config.md
This is a first attempt at https://github.com/influxdb/influxdb.com/issues/153. 
There are a couple things to note/please comment on:
* Is the current layout OK or is the structure of the [v0.8 config doc](https://influxdb.com/docs/v0.8/advanced_topics/configuration_options.html) preferable?
* 🎁s mark where I wasn't sure what to write - it covers areas where I don't know what the options do as well as areas where it might be good to put a note about what works for most systems (but I wasn't sure what that was). Any knowledge gifts are appreciated!
* I linked to whatever documentation we have for the plugins but, in general, I left those sections well alone.
* I made all of my changes to administration/config.md - happy to make this a whole new page if that's preferred.
> restructure the config doc and add material [WIP]

- content/docs/kapacitor/v0.1/tick/expr.md
Updates Kapacitor docs for supported math functions.
> Add information on available math functions

- content/docs/kapacitor/v0.1/examples/join_backfill.md
- content/docs/kapacitor/v0.1/examples/live_leaderboard.md
- content/docs/kapacitor/v0.1/introduction/getting_started.md
- content/docs/kapacitor/v0.1/tick/join_node.md
- content/docs/kapacitor/v0.1/tick/stream_node.md
- content/docs/kapacitor/v0.1/tick/syntax.md
- content/docs/kapacitor/v0.1/tick/union_node.md
Changed the format of the from statement to be explicit so that you don't have to worry about weird double parsing errors. See https://github.com/influxdb/kapacitor/pull/59
> update docs for new from format

- content/docs/v0.9/guides/clustering.md
Fixes https://github.com/influxdb/influxdb.com/issues/451
@beckettsean
> Note cluster meta-queries are working in 0.9.5

- content/site/download.md
- layouts/partials/docs/v0.9/sidebar.html
NOTE: These download links and MD5Sums are not correct yet. Still need to build and publish final binary for release. I'll update this PR once its ready.
> update downloads for Kapacitor
